# Generated by Django 4.0.5 on 2022-06-26 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=6, unique=True)),
                ('name', models.TextField()),
                ('imageUrl', models.TextField()),
            ],
        ),
    ]
