# Generated by Django 3.2.13 on 2022-06-30 11:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunnels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tunnel',
            name='emailNotify',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tunnel',
            name='bottomLimit',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='tunnel',
            name='frequency',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(59)]),
        ),
        migrations.AlterField(
            model_name='tunnel',
            name='topLimit',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
